Repository ON-AIR-mate/Android, pull requests merged in 2025-08, with the labels that each got.

#16 Feature/친구 드롭다운이벤트구현
  app/src/main/java/umc/OnAirMate/ui/friend/list/FriendItemClickListener.kt
  app/src/main/java/umc/OnAirMate/ui/util/TimeFormatter.kt
  app/src/main/java/umc/onairmate/data/model/entity/UserData.kt
  app/src/main/java/umc/onairmate/ui/friend/FriendViewModel.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendListRVAdapter.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendListTabFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendRequestViewHolder.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendViewHolder.kt
  app/src/main/java/umc/onairmate/ui/friend/search/SearchFriendTabFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/search/SearchUserRVAdapter.kt
  app/src/main/res/drawable/background_box_3dp.xml
  app/src/main/res/layout/fragment_friend_list_tab.xml
  app/src/main/res/layout/fragment_search_friend_tab.xml
  app/src/main/res/layout/popup_friend_options.xml
  app/src/main/res/layout/rv_item_friend.xml
Labels: :star2: Feature, 📬 API

#18 Featrue/채팅 socket모듈구현
  app/build.gradle.kts
  app/src/main/java/umc/OnAirMate/data/api/ChatRoomService.kt
  app/src/main/java/umc/OnAirMate/data/model/entity/ChatMessageData.kt
  app/src/main/java/umc/OnAirMate/data/model/response/SocketResponse.kt
  app/src/main/java/umc/OnAirMate/data/repository/repository/ChatRoomRepository.kt
  app/src/main/java/umc/OnAirMate/data/repository/repositoryImpl/ChatRoomRepositoryImpl.kt
  app/src/main/java/umc/OnAirMate/data/socket/SocketDispatcher.kt
  app/src/main/java/umc/OnAirMate/data/socket/SocketHandler.kt
  app/src/main/java/umc/OnAirMate/data/socket/SocketManager.kt
  app/src/main/java/umc/OnAirMate/data/socket/handler/ChatRoomHandler.kt
  app/src/main/java/umc/OnAirMate/data/socket/listener/ChatRoomEventListener.kt
  app/src/main/java/umc/OnAirMate/data/socket/listener/RoomEventListener.kt
  app/src/main/java/umc/OnAirMate/data/util/parseJson.kt
  app/src/main/java/umc/OnAirMate/ui/chat_room/ChatRoomFragment.kt
  app/src/main/java/umc/OnAirMate/ui/chat_room/message/ChatRVAdapter.kt
  app/src/main/java/umc/OnAirMate/ui/chat_room/message/FragmentVideoChat.kt
  app/src/main/java/umc/OnAirMate/ui/chat_room/message/VideoChatFragment.kt
  app/src/main/java/umc/OnAirMate/ui/chat_room/message/VideoChatViewModel.kt
  app/src/main/java/umc/onairmate/OnAirMateApplication.kt
  app/src/main/java/umc/onairmate/data/api/HomeService.kt
  app/src/main/java/umc/onairmate/data/repository/repository/HomeRepository.kt
  app/src/main/java/umc/onairmate/data/repository/repositoryImpl/HomeRepositoryImpl.kt
  app/src/main/java/umc/onairmate/ui/MainActivity.kt
  app/src/main/java/umc/onairmate/ui/TestViewModel.kt
  app/src/main/java/umc/onairmate/ui/home/HomeFragment.kt
  app/src/main/java/umc/onairmate/ui/login/LoginActivity.kt
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/values/strings.xml
Labels: :bug: BugFix, 📬 API

#22 fix: 회원가입 페이지에서 로그인 페이지 이동
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/OnAirMate/data/api/JoinService.kt
  app/src/main/java/umc/OnAirMate/data/model/request/JoinProfileRequest.kt
  app/src/main/java/umc/OnAirMate/data/model/response/JoinProfileResponse.kt
  app/src/main/java/umc/OnAirMate/data/model/response/NicknameCheckResponse.kt
  app/src/main/java/umc/OnAirMate/data/repository/repository/JoinRepository.kt
  app/src/main/java/umc/OnAirMate/data/repository/repositoryImpl/JoinRepositoryImpl.kt
  app/src/main/java/umc/OnAirMate/ui/chat_room/ChatRoomFragment.kt
  app/src/main/java/umc/OnAirMate/ui/join/JoinViewModel.kt
  app/src/main/java/umc/OnAirMate/ui/join/model/JoinCollection.kt
  app/src/main/java/umc/onairmate/module/NetworkModule.kt
  app/src/main/java/umc/onairmate/module/RepositoryModule.kt
  app/src/main/java/umc/onairmate/ui/SplashActivity.kt
  app/src/main/java/umc/onairmate/ui/join/HowToUseFragment.kt
  app/src/main/java/umc/onairmate/ui/join/JoinFragment.kt
  app/src/main/java/umc/onairmate/ui/join/JoinProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/login/LoginActivity.kt
  app/src/main/java/umc/onairmate/ui/login/LoginViewModel.kt
  app/src/main/java/umc/onairmate/ui/lounge/CollectionListFragment.kt
  app/src/main/java/umc/onairmate/ui/lounge/model/Collection.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_how_to_use.xml
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_join_profile.xml
  app/src/main/res/navigation/nav_graph.xml
  gradlew
Labels: :bug: BugFix, :star2: Feature

#32 Feature/채팅 개인메시지
  app/src/main/java/umc/onairmate/data/api/FriendService.kt
  app/src/main/java/umc/onairmate/data/model/entity/DirectMessageData.kt
  app/src/main/java/umc/onairmate/data/model/entity/FriendData.kt
  app/src/main/java/umc/onairmate/data/model/entity/SocketMessage.kt
  app/src/main/java/umc/onairmate/data/model/request/FriendInviteRequest.kt
  app/src/main/java/umc/onairmate/data/repository/repository/FriendRepository.kt
  app/src/main/java/umc/onairmate/data/repository/repositoryImpl/FriendRepositoryImpl.kt
  app/src/main/java/umc/onairmate/data/socket/SocketDispatcher.kt
  app/src/main/java/umc/onairmate/data/socket/SocketManager.kt
  app/src/main/java/umc/onairmate/data/socket/handler/ChatRoomHandler.kt
  app/src/main/java/umc/onairmate/data/socket/handler/FriendHandler.kt
  app/src/main/java/umc/onairmate/data/socket/listener/ChatRoomEventListener.kt
  app/src/main/java/umc/onairmate/data/socket/listener/FriendEventListener.kt
  app/src/main/java/umc/onairmate/module/NetworkModule.kt
  app/src/main/java/umc/onairmate/module/RepositoryModule.kt
  app/src/main/java/umc/onairmate/module/ServiceModule.kt
  app/src/main/java/umc/onairmate/ui/chat_room/drawer/ChatRoomDrawerFragment.kt
  app/src/main/java/umc/onairmate/ui/chat_room/message/VideoChatViewModel.kt
  app/src/main/java/umc/onairmate/ui/friend/FriendFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/FriendViewModel.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/CollectionChatViewHolder.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/FriendChatActivity.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/FriendChatEventListener.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/FriendChatFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/FriendChatRVAdapter.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/FriendChatViewModel.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/InviteChatViewHolder.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendListTabFragment.kt
  app/src/main/java/umc/onairmate/ui/lounge/collection/CollectionListFragment.kt
  app/src/main/res/layout/rv_item_collection_chat.xml
  app/src/main/res/layout/rv_item_invite_chat.xml
  app/src/main/res/values/style.xml
Labels: :star2: Feature, 📬 API

#36 Feature/프로필 이미지등록
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/onairmate/data/api/ImageService.kt
  app/src/main/java/umc/onairmate/data/model/request/ProfileRequest.kt
  app/src/main/java/umc/onairmate/data/model/response/ImageResponse.kt
  app/src/main/java/umc/onairmate/data/repository/repository/ImageRepository.kt
  app/src/main/java/umc/onairmate/data/repository/repositoryImpl/ImageRepositoryImpl.kt
  app/src/main/java/umc/onairmate/data/util/UriToMultipartUtil.kt
  app/src/main/java/umc/onairmate/module/RepositoryModule.kt
  app/src/main/java/umc/onairmate/module/ServiceModule.kt
  app/src/main/java/umc/onairmate/ui/ImageViewModel.kt
  app/src/main/java/umc/onairmate/ui/join/JoinProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/profile/ProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/util/ImagePickerDelegate.kt
  app/src/main/java/umc/onairmate/ui/util/ImagePickerDelegateForActivity.kt
Labels: :star2: Feature

#37 Feature/수정 2차qa수정
  app/src/main/java/umc/onairmate/ui/chat_room/drawer/participants/ChatRoomParticipantsFragment.kt
  app/src/main/java/umc/onairmate/ui/profile/ProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/util/NetworkImageLoader.kt
  app/src/main/res/drawable/background_logout.xml
  app/src/main/res/drawable/ic_alarm_off.png
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_empty_profile.png
  app/src/main/res/drawable/ic_onairmate_logo_bottom.png
  app/src/main/res/drawable/ic_onairmate_logo_bottom.xml
  app/src/main/res/drawable/ic_popular.png
  app/src/main/res/drawable/ic_popular.xml
  app/src/main/res/drawable/ic_question.png
  app/src/main/res/drawable/ic_question.xml
  app/src/main/res/drawable/ic_search.png
  app/src/main/res/drawable/img.png
  app/src/main/res/drawable/logo_onairmate.png
  app/src/main/res/drawable/logo_onairmate_profile.png
  app/src/main/res/drawable/logo_onairmate_typo.png
  app/src/main/res/drawable/onairmate_logo.png
  app/src/main/res/drawable/profile.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_how_to_use.xml
  app/src/main/res/layout/fragment_join_profile.xml
  app/src/main/res/layout/fragment_personal_info.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_video_search.xml
  app/src/main/res/layout/rv_item_bookmark.xml
  app/src/main/res/layout/rv_item_chat_room_user.xml
Labels: 🔨 Refactor

#39 Featrue/로딩 프로그래스바추가
  app/src/main/java/umc/onairmate/data/api/AuthService.kt
  app/src/main/java/umc/onairmate/ui/ImageViewModel.kt
  app/src/main/java/umc/onairmate/ui/chat_room/ChatRoomLayoutActivity.kt
  app/src/main/java/umc/onairmate/ui/chat_room/ChatVideoViewModel.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendListTabFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/search/SearchFriendTabFragment.kt
  app/src/main/java/umc/onairmate/ui/home/HomeFragment.kt
  app/src/main/java/umc/onairmate/ui/home/HomeViewModel.kt
  app/src/main/java/umc/onairmate/ui/home/video/SearchVideoViewModel.kt
  app/src/main/java/umc/onairmate/ui/home/video/VideoSearchFragment.kt
  app/src/main/java/umc/onairmate/ui/join/JoinProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/login/LoginActivity.kt
  app/src/main/java/umc/onairmate/ui/login/LoginFragment.kt
  app/src/main/java/umc/onairmate/ui/login/LoginViewModel.kt
  app/src/main/java/umc/onairmate/ui/lounge/collection/CollectionListFragment.kt
  app/src/main/java/umc/onairmate/ui/lounge/collection/detail/CollectionDetailFragment.kt
  app/src/main/java/umc/onairmate/ui/pop_up/LoadingDialogFragment.kt
  app/src/main/java/umc/onairmate/ui/profile/ProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/util/LoadingDialogUtil.kt
  app/src/main/res/layout/activity_chat_room_layout.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_bookmark_list.xml
  app/src/main/res/layout/fragment_collection_detail.xml
  app/src/main/res/layout/fragment_collection_list.xml
  app/src/main/res/layout/fragment_friend_list_tab.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_how_to_use.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_search_friend_tab.xml
  app/src/main/res/layout/fragment_video_chat.xml
  app/src/main/res/layout/fragment_video_search.xml
  app/src/main/res/values/themes.xml
Labels: :star2: Feature

#40 chore: 파일정리 + 주석 정리
  app/src/main/java/umc/onairmate/OnAirMateApplication.kt
  app/src/main/java/umc/onairmate/data/socket/SocketDispatcher.kt
  app/src/main/java/umc/onairmate/data/socket/SocketManager.kt
  app/src/main/java/umc/onairmate/data/util/UriToMultipartUtil.kt
  app/src/main/java/umc/onairmate/ui/ImageViewModel.kt
  app/src/main/java/umc/onairmate/ui/chat_room/message/VideoChatFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/FriendFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/FriendViewModel.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/FriendChatFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/chat/InviteChatViewHolder.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendListRVAdapter.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendListTabFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/search/SearchFriendTabFragment.kt
  app/src/main/java/umc/onairmate/ui/home/HomeFragment.kt
  app/src/main/java/umc/onairmate/ui/home/HomeViewModel.kt
  app/src/main/java/umc/onairmate/ui/home/RecommendedVideoRVAdapter.kt
  app/src/main/java/umc/onairmate/ui/home/SearchTypeSpinnerAdapter.kt
  app/src/main/java/umc/onairmate/ui/join/HowToUseFragment.kt
  app/src/main/java/umc/onairmate/ui/join/JoinFragment.kt
  app/src/main/java/umc/onairmate/ui/join/JoinProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/pop_up/LoadingDialogFragment.kt
  app/src/main/java/umc/onairmate/ui/util/ImagePickerDelegate.kt
  app/src/main/java/umc/onairmate/ui/util/ImagePickerDelegateForActivity.kt
  app/src/main/java/umc/onairmate/ui/util/LoadingDialogUtil.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/navigation/mobile_navigation2.xml
Labels: :memo: Docs

#43 Feature/3차qa수정
  app/build.gradle.kts
  app/src/main/java/umc/onairmate/data/api/NotificationService.kt
  app/src/main/java/umc/onairmate/data/model/entity/NotificationData.kt
  app/src/main/java/umc/onairmate/data/model/response/NotificationResponse.kt
  app/src/main/java/umc/onairmate/data/model/response/ReadCountResponse.kt
  app/src/main/java/umc/onairmate/data/repository/repository/NotificationRepository.kt
  app/src/main/java/umc/onairmate/data/repository/repositoryImpl/NotificationRepositoryImpl.kt
  app/src/main/java/umc/onairmate/module/RepositoryModule.kt
  app/src/main/java/umc/onairmate/module/ServiceModule.kt
  app/src/main/java/umc/onairmate/ui/MainActivity.kt
  app/src/main/java/umc/onairmate/ui/NavViewModel.kt
  app/src/main/java/umc/onairmate/ui/NavigationExtensions.kt
  app/src/main/java/umc/onairmate/ui/chat_room/drawer/participants/ChatRoomParticipantRVAdapter.kt
  app/src/main/java/umc/onairmate/ui/chat_room/drawer/participants/ChatRoomParticipantsFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/FriendFragment.kt
  app/src/main/java/umc/onairmate/ui/friend/list/FriendViewHolder.kt
  app/src/main/java/umc/onairmate/ui/home/HomeFragment.kt
  app/src/main/java/umc/onairmate/ui/home/notification/NotificationFragment.kt
  app/src/main/java/umc/onairmate/ui/home/notification/NotificationRVAdapter.kt
  app/src/main/java/umc/onairmate/ui/home/notification/NotificationViewModel.kt
  app/src/main/java/umc/onairmate/ui/home/video/VideoSearchFragment.kt
  app/src/main/java/umc/onairmate/ui/profile/ProfileFragment.kt
  app/src/main/java/umc/onairmate/ui/util/TimeFormatter.kt
  app/src/main/res/drawable/ic_has_change.xml
  app/src/main/res/drawable/ic_onairmate_logo_bottom.xml
  app/src/main/res/drawable/ic_speech_bubble_top.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/popup_friend_options.xml
  app/src/main/res/layout/popup_participant_options.xml
  app/src/main/res/layout/popup_tooltip.xml
  app/src/main/res/layout/rv_item_notification.xml
  app/src/main/res/navigation/nav_friend.xml
  app/src/main/res/navigation/nav_home.xml
  app/src/main/res/navigation/nav_notification.xml
  gradle/libs.versions.toml
Labels: :bug: BugFix, 🔨 Refactor

#45 Feature/채팅방 ai요약 구현
  app/build.gradle.kts
  app/src/main/java/umc/OnAirMate/data/model/entity/EmotionAnalysis.kt
  app/src/main/java/umc/OnAirMate/data/model/request/SummaryCreateRequest.kt
  app/src/main/java/umc/OnAirMate/data/model/request/SummaryFeedbackRequest.kt
  app/src/main/java/umc/OnAirMate/data/model/response/SummaryCreateResponse.kt
  app/src/main/java/umc/OnAirMate/ui/chat_room/summary/SummaryFragment.kt
  app/src/main/java/umc/onairmate/data/api/ChatRoomService.kt
  app/src/main/java/umc/onairmate/data/repository/repository/ChatRoomRepository.kt
  app/src/main/java/umc/onairmate/data/repository/repositoryImpl/ChatRoomRepositoryImpl.kt
  app/src/main/java/umc/onairmate/ui/chat_room/ChatRoomFragment.kt
  app/src/main/java/umc/onairmate/ui/chat_room/ChatRoomTerminateDialog.kt
  app/src/main/java/umc/onairmate/ui/chat_room/ChatVideoViewModel.kt
  app/src/main/java/umc/onairmate/ui/pop_up/CreateRoomPopup.kt
  app/src/main/res/drawable/ic_thumbs_down.xml
  app/src/main/res/drawable/ic_thumbs_up.xml
  app/src/main/res/layout/dialog_terminate_room.xml
  app/src/main/res/layout/fb_item_feeling.xml
  app/src/main/res/layout/fragment_summary.xml
  app/src/main/res/values/colors.xml
  gradle/libs.versions.toml
Labels: :star2: Feature, 📬 API

#46 Feature/북마크 데이터 구조 변경에 따른 로직 수정
  app/src/main/java/umc/onairmate/data/model/entity/CollectionDetailData.kt
  app/src/main/java/umc/onairmate/ui/chat_room/ChatRoomFragment.kt
  app/src/main/java/umc/onairmate/ui/chat_room/drawer/participants/ChatRoomParticipantsFragment.kt
  app/src/main/java/umc/onairmate/ui/lounge/bookmark/BookmarkListFragment.kt
  app/src/main/java/umc/onairmate/ui/lounge/bookmark/move/CollectionMoveDialog.kt
  app/src/main/java/umc/onairmate/ui/lounge/collection/CollectionListFragment.kt
  app/src/main/java/umc/onairmate/ui/lounge/collection/detail/CollectionDetailFragment.kt
  app/src/main/java/umc/onairmate/ui/lounge/collection/detail/CollectionDetailRVAdapter.kt
  app/src/main/java/umc/onairmate/ui/lounge/collection/detail/CollectionDetailViewHolder.kt
  app/src/main/java/umc/onairmate/ui/util/NetworkImageLoader.kt
  app/src/main/java/umc/onairmate/ui/util/TimeFormatter.kt
  app/src/main/res/drawable/ic_empty.xml
  app/src/main/res/drawable/ic_empty_collection.xml
  app/src/main/res/layout/activity_participated_rooms.xml
  app/src/main/res/layout/fragment_bookmark_list.xml
  app/src/main/res/layout/fragment_collection_list.xml
  app/src/main/res/layout/fragment_friend_list_tab.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search_friend_tab.xml
  app/src/main/res/layout/rv_item_collection.xml
  app/src/main/res/layout/rv_item_collection_detail.xml
  app/src/main/res/layout/rv_item_collection_detail_empty.xml
Labels: :star2: Feature, 📬 API
